### ISSUE TITLE
Update standar penggajian

### ISSUE THREAD

**Issue by priyandari** [elvabunga/Kelompok-05#3]
Akan lebih baik kalau bisa melakukan update standar2 nilai pengajian (gaji pokok, lembur dan lain2)

**Comment by I0318080-RizkiAnandaPutraNurRohmat** [comment]
diatasi dengan pemberian pertanyaan awal berupa input data data seperti gaji pokok, tunjangan, dsb.

**Comment by priyandari** [comment]
Itu semua sebelum input pegawai di tanya satu persatu?
Maksud saya ada menu khusus untuk update data STANDAR PENGGAJIAN

**Comment by elvabunga** [comment]
Menu untuk mengupdate standar penggajian sudah dipisahkan, sehingga user dapat menggunakan standar penggajian yang tersedia maupun standar yang baru.

**Comment by priyandari** [comment]
Ok
